# Introducción al uso de Python

PROCEDIMIENTO

a. Cree el siguiente par de vectores:

a = [3.1,1, -0.5, -3.2, 6], b= [1, 3, 2.2, 5.1, 1]



In [1]:
import numpy as np

In [3]:
a = np.array([3.1,1,-0.5,-3.2,6])
b = np.array([1,3,2.2,5.1,1])

print("Vector a: ", a)
print("Vector b: ", b)

Vector a:  [ 3.1  1.  -0.5 -3.2  6. ]
Vector b:  [1.  3.  2.2 5.1 1. ]



b. Implemente la multiplicación escalar de a.b ¿Qué se debe realizar para poder multiplicar los dos vectores?

R/ La condicición es que los dos vectores deben tener la misma dimensión (igual número de elementos).

Aquí ambos tienen 5 elementos entonces sí se puede realizar la multiplicación de vectores

In [5]:
producto_escalar = np.dot(a, b)
print("Producto escalar:", producto_escalar)

Producto escalar: -5.32


c. Implemente la multiplicación punto a punto de a.b.

In [8]:
mult_esc = a*b
print("Multiplicación punto a punto: ", mult_esc)

Multiplicación punto a punto:  [  3.1    3.    -1.1  -16.32   6.  ]


d. Contruya la matriz 

In [11]:
matrizA = np.array([[2,-1,-3],[4,1.5,-2.5],[7.3,-0.9,0.2]])
print("matriz A: \n", matrizA)

matriz A: 
 [[ 2.  -1.  -3. ]
 [ 4.   1.5 -2.5]
 [ 7.3 -0.9  0.2]]


e. Obtenga su transpuesta AT.

In [15]:
matrizTransp = np.transpose(matrizA)
print(matrizTransp)

[[ 2.   4.   7.3]
 [-1.   1.5 -0.9]
 [-3.  -2.5  0.2]]


f. Consulte la función de los siguientes comandos de la librería numpy: ones, round, ceil, floor, implemente cada función para ejemplificar su uso.

In [ ]:
# ones: Crea un arreglo lleno de unos (1) con la forma que le indiquemos.
ones = np.ones((2, 3)) 
print("\n Matriz de unos: \n", ones)

# round: Redondea los valores decimales al número de decimales indicado.
round = np.round(1.87899, 3)
print("\n Redondeado:", round)

# ceil: Redondea hacia arriba al entero más cercano.
ceil = np.ceil(matrizA)
print("\n Ceil: \n", ceil)

# floor: Redondea hacia abajo al entero más cercano.
floor = np.floor(matrizA)
print("\n Floor: \n", floor)


 Matriz de unos: 
 [[1. 1. 1.]
 [1. 1. 1.]]

 Redondeado: 1.879

 Ceil: 
 [[ 2. -1. -3.]
 [ 4.  2. -2.]
 [ 8. -0.  1.]]

 Floor: 
 [[ 2. -1. -3.]
 [ 4.  1. -3.]
 [ 7. -1.  0.]]


g. Acceda al valor de la primera fila, tercera columna de la matriz A, imprímalo en consola.

In [20]:
print("Valor de la primera fila, tercera columna de la matriz A:" , matrizA[0,2])

Valor de la primera fila, tercera columna de la matriz A: -3.0


h. Obtenga la segunda fila de dicha matriz, imprímalo en consola.

In [21]:
print("Segunda fila de la matriz A: \n", matrizA[1])

Segunda fila de la matriz A: 
 [ 4.   1.5 -2.5]



i. Consulte el comando para conocer las dimensiones de una matriz, utilícelo con la matriz A e imprímalo en consola.